Update README.md
build by option 2:use native compiler exits problem:
Attempted to execute and encountered an error indicating that the stdint.h header file was missing when using the native compiler. The command "riscv64-unknown-elf-gcc" did not execute successfully (status code exit status: 1).

The error message displayed:

running: "riscv64-unknown-elf-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-march=rv64imac" "-mabi=lp64" "-mcmodel=medany" "-Wall" "-Wextra" "-o" "/workspace/ckb-combine-lock-poc/target/riscv64imac-unknown-none-elf/release/build/blake2b-rs-5e7a969012c3c223/out/BLAKE2/ref/blake2b-ref.o" "-c" "BLAKE2/ref/blake2b-ref.c"
cargo:warning=In file included from BLAKE2/ref/blake2b-ref.c:16:
cargo:warning=/usr/lib/gcc/riscv64-unknown-elf/10.2.0/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
cargo:warning=    9 | # include_next <stdint.h>
cargo:warning=      |                ^~~~~~
cargo:warning=compilation terminated.
exit status: 1

--- stderr

The operating system environment used was Ubuntu with kernel version 5.15.0-47-generic.

To reproduce the issue, the following steps were taken:

rustup target add riscv64imac-unknown-none-elf
sudo apt install gcc-riscv64-unknown-elf
cargo build --release --target riscv64imac-unknown-none-elf